### ISSUE TITLE
Add Login And Status Info To Readme

### ISSUE THREAD

**Issue by alexfinnarn** [weknowinc/drupal-boina#2]
After running the commands in the readme I did end up with a functional site, but I had to guess the admin login afterwards. It would be nice to add a section after the commands to inform the user of logging in info.

Also, I thought the https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/site-status.html command would be available for me to run. It is a nice command to have, and some sort of `ahoy boina:status` command could provide output like the URL of the site and other health checks. 

In lieu of a status command, you could tell people to go to http://drupal-boina.weknowinc.com/ to know that it looks right. 

I can make a PR for adding some of these things to the readme, but do you have thoughts on this first? I am coming at this from a "I don't know anything about anything" perspective and trying to give as much context to the person trying to install it.

**Comment by jmolivas** [comment]
@alexfinnarn we can probably add instructions to:
- Reset password
```
ahoy drupal user:password:reset admin [ENTER_YOUR_DESIRE_PASSWORD]
```
- Generate a login link using
```
ahoy drupal user:login:url admin
```

**Comment by jmolivas** [comment]
@alexfinnarn: Fixed with https://github.com/weknowinc/drupal-boina/pull/15
