### ISSUE TITLE
Updates Needed On Status Report After Install

### ISSUE THREAD

**Issue by alexfinnarn** [weknowinc/drupal-boina#3]
I went to the status report as is my habit after installing any Drupal site, and I saw that there were updates needed. 

- Drupal 8.6.7 -> 8.6.8 https://www.drupal.org/project/drupal/releases/8.6.8
- Admin Toolbar 8.x-1.25 -> 8.x-1.26 https://www.drupal.org/project/admin_toolbar/releases/8.x-1.26

**Comment by jmolivas** [comment]
@alexfinnarn Updated done. Latest core and will doublecheck modules.

**Comment by jmolivas** [comment]
We are on latest 
- Drupal core 8.7.6
-Using JSON:API from core and no longer as contributed module

![image](https://user-images.githubusercontent.com/366275/62808345-ac567800-baac-11e9-8506-f4da78eefdc7.png)

PR:
- https://github.com/weknowinc/drupal-boina/pull/13
- https://github.com/weknowinc/drupal-boina/pull/14
