### ISSUE TITLE
Update composer.json to use new composer-patches option

### ISSUE THREAD

**Issue by benjifisher** [weknowinc/drupal-boina#5]
I noticed that `composer.json` in the current project requires `cweagans/composer-patches` but does not configure the patch level for `drupal/core`. This can lead to problems when applying patches for Drupal core: see https://github.com/cweagans/composer-patches/issues/43. In order to avoid these problems, add a few lines to `composer.json` as in https://github.com/drupal-composer/drupal-project/pull/418.

**Comment by jmolivas** [comment]
@GuidoRobertone can you please take care of this request?

**Comment by jmolivas** [comment]
Fixed with https://github.com/weknowinc/drupal-boina/pull/7
